name: Build flipDashboard

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build flipDashboard
    permissions:
      checks: write
      contents: read
    uses: Displayr/nixr-public/.github/workflows/build-flake-installable.yaml@master
    with:
      installable-path: pkgs.x86_64-linux.rPackages.flipDashboard
      build-args: --override-input flipDashboard .
      installable-name: flipDashboard
    secrets: inherit
